apiVersion: v1
kind: Service
metadata:
  name: attendance-reconciliation-service
spec:
  type: NodePort
  selector:
    app: attendance-reconciliation
  ports:
  - protocol: TCP
    port: 2011
    targetPort: 2011
