name: Python Syntax Check, Docker Build, Push, and Deploy to Minikube

on:
  push:
    branches:
      - '*'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start the pipeline
        run: echo "Starting the pipeline..."

  check_python_syntax:
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checking Python syntax
        run: |
          for file in $(find . -name "*.py"); do
            echo "Checking $file"
            python -m py_compile "$file" || { echo "Syntax error in $file"; exit 1; }
          done

  build_and_push_docker_image:
    runs-on: ubuntu-latest
    needs: check_python_syntax
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mazid262/your-image-name:latest

  deploy_to_minikube:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.21.0'

      - name: Deploy Docker image to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Access Minikube service
        run: |
          minikube service your-service --url

  end:
    runs-on: ubuntu-latest
    needs: deploy_to_minikube
    steps:
      - name: End the pipeline
        run: echo "Pipeline finished."
