name: Python Syntax Check, Docker Build, Push, and Deploy to Minikube

on:
  push:
    branches:
      - '*'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start the pipeline
        run: echo "Starting the pipeline..."

  check_python_syntax:
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checking Python syntax
        run: |
          for file in $(find . -name "*.py"); do
            echo "Checking $file"
            python -m py_compile "$file" || { echo "Syntax error in $file"; exit 1; }
          done

  run_tests:
    runs-on: ubuntu-latest
    needs: check_python_syntax
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest --maxfail=1 --disable-warnings -q --cov=your_package_name --cov-report=xml

      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml

      - name: Run code quality checks
        run: |
          pylint your_package_name
          flake8 your_package_name

  build_and_push_docker_image:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mazid262/attendance-data-reconciliation:latest

  end:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    steps:
      - name: End the pipeline
        run: echo "Pipeline finished."
