name: Docker Build and Push

on:
  push:
    branches:
      - '*'

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mazid262/your-image-name:latest

  end:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    steps:
      - name: End the pipeline
        run: echo "Docker build and push pipeline finished."
